# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  - curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) r-cran-gettz
  - sudo add-apt-repository -y ppa:edd/misc
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-bh r-cran-gettz

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

after_success:
   # r-cran-covr is available in the Rutter PPAs we know about
   - ./run.sh install_aptget r-cran-covr        
   - R -e 'covr::codecov()'
   
notifications:
  email:
    on_success: change
    on_failure: change

    

